[package]
name = "bip39"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "*" 
bip32 = "*"
bip39 = { version = "*", features = ["all-languages"] }
bitcoin = "*"
block-modes = "*"
bs58 = "*"
comfy-table = "*"
crossterm = "*"
hex = "*"
hmac = "*"
parking_lot = "*"
pbkdf2 = "*"
rand = { version = "0.8", features = ["std"] }
ratatui = "*"
ripemd160 = "*"
secp256k1 = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
sha2 = "*"
sskr = "*"
terminal_size = "*"
tiny-keccak = { version = "*", features = ["keccak"] }


